version = 0.1
[default.deploy.parameters]
stack_name = "wow-extension-backend"
resolve_s3 = true
s3_prefix = "wow-extension-backend"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
