name: Dependabot Auto Merge

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    if: github.actor == 'dependabot'
    runs-on: ubuntu-latest
    steps:
      - name: Dependabot Auto Merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          merge-method: squash
          approve: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}